[project]
name = "poc-streamlit-s3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"streamlit>=1.41",
	"streamlit-aggrid>=0.3.4",
	"boto3>=1.35",
	"pandas>=2.2",
	"pyarrow>=17.0",
]
